### ISSUE TITLE
请修及时改博客相关信息

### ISSUE THREAD

**Issue by ImCa0** [yujunhuics/yujunhuics.github.io#1]
你好👋，我在百度统计中看到了来自这里的流量，欢迎你复刻我的博客，请及时修改以下内容：

- 百度统计代码
- 底部备案信息
- 删除或修改文章（若需保留文章请注意转载信息）及页面（包括足迹、站点历程、博客统计、友链页面的申请方式等包含个人信息的内容）

如果在开发过程中遇到问题，欢迎与我交流，感谢使用！

**Comment by yujunhuics** [comment]
你好，
      已收到来信，感谢开源，在参考留言板配置过程中没注意带来不便敬请谅解，已去除该API密钥，欢迎持续关注。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年04月26日 16:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [yujunhuics/yujunhuics.github.io] 请修及时改博客相关信息 (Issue #1) |

你好👋，我在百度统计中看到了来自这里的流量，欢迎你复刻我的博客，请及时修改以下内容：

百度统计代码
底部备案信息
删除或修改文章（若需保留文章请注意转载信息）及页面（包括足迹、站点历程、博客统计、友链页面的申请方式等包含个人信息的内容）

如果在开发过程中遇到问题，欢迎与我交流，感谢使用！
